-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "geoSource" TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "lastGeoCheck" TIMESTAMP(3);
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "lastGeoIp" TEXT;
